### PR TITLE
Fix /snapshot response to work with obico

### LINKED ISSUE #31: Implement snapshot
**Is your feature request related to a problem? Please describe.**
In OctoPrint Stream-URL works perfectly with http://ip-addr:8080/video_feed. But this address doesn't work for Snapshot-URL. 

**Describe the solution you'd like**
I would like to have an URL like  http://ip-addr:8080/snapshot or similar. This would be nice for time lapses.

**Additional context**
grafik

### PR DESCRIPTION
**Pull request by nvtkaszpir**
Fixes #31

### CODE REVIEW

**Comment by nvtkaszpir** [comment]
hm there are still some weird timeouts, changing to draft.

**Comment by monkeymademe** [comment]
I would like to make your current changes anyways even if it does not work for obico because what you pointed out is generally better

**Comment by nvtkaszpir** [comment]
do  whatever you like with it.

**Comment by nvtkaszpir** [comment]
the issues are caused by werkzeug lib,when runnin `python app.py` and when doing too much operations/requests then it ends in some race condtition and ends with RuntimeError, after which it does not process any requests

**Pull request merged**
